### ISSUE TITLE
Signaler le dépôt dans HTR-United

### ISSUE THREAD

**Issue by alix-tz** [jpmjpmjpm/genauto-td-htr#2]
Pour signaler le dépôt dans HTR-United, vous pouvz copier-coller le contenu de `htr-united.yml` dans une issue, sur le modèle de cette proposition : https://github.com/HTR-United/htr-united/issues/21

Je m'occuperai ensuite d'ajouter la description dans le répo principal

**Comment by jpmjpmjpm** [comment]
Issue [#13](https://github.com/HTR-United/htr-united/issues/23#issue-996121012) was created in [HTR United](https://github.com/HTR-United/htr-united.git).

This closes the current issue.
