### ISSUE TITLE
Ajouter des badges avec HUM generator (optionnel)

### ISSUE THREAD

**Issue by alix-tz** [jpmjpmjpm/genauto-td-htr#3]
Si vous le souhaitez, vous pouvez ajouter des badges indicant dynamiquement le nombre de caractères, lignes et régions dans le dépôt. 

HUM-generator devrait marcher en dehors de l'organisation Github, voici le tutoriel : https://github.com/HTR-United/htr-united-metadata-generator/blob/main/TUTORIAL.md

L'idée est d'ajouter des éléments comme ceux-ci :  

![image](https://user-images.githubusercontent.com/33317799/133280644-d59d1fc9-6745-4032-a872-8c1effc45d23.png)

**Comment by jpmjpmjpm** [comment]
@alix-tz Alix, j'essaye de mettre en place ces badges. Je dois ne pas être loin du but car le script [humg.py](https://github.com/HTR-United/htr-united-metadata-generator/blob/658c9138365a417371f81e05fd0041471bcecab8/humg.py) tourne bien.

Si tu vas dans les [actions](https://github.com/jpmjpmjpm/genauto-td-htr/actions), tu verras que les statistiques sont bien générées. Par contre, il y a un problème dans la dernière étape pour récupérer les données du fichier `envs.txt` dans la ligne `cat envs.txt >> $GITHUB_ENV`.

Je n'ai d'ailleurs pas créé ce fichier. Faut-il le créer? Et si oui, où?

Merci pour ton aide!

**Comment by jpmjpmjpm** [comment]
@alix-tz Ne tient pas compte de mon message précédent... J'ai trouvé l'erreur!

**Comment by jpmjpmjpm** [comment]
Closed within commit 8153e30.
